# -*- coding: utf-8 -*-
import sys
import unittest
from pathlib import Path
from unittest.mock import Mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "runtime-patches"))
from development_tools import _branch_name, _git


class BranchSafetyTests(unittest.TestCase):
    def test_valid_backup(self):
        self.assertEqual(_branch_name("backup/agent-safe"), "backup/agent-safe")

    def test_autogenerated_backup(self):
        value = _branch_name("")
        self.assertTrue(value.startswith("backup/agent-"))
        self.assertLessEqual(len(value), 100)

    def test_invalid_names(self):
        invalid = [
            "main", "backup/../main", "backup//foo", "backup/foo.lock",
            "backup/foo/", "backup/foo@{bar", "backup/foo..bar",
            "backup/foo bar", "backup/foo\\bar",
        ]
        for name in invalid:
            with self.subTest(name=name), self.assertRaises(ValueError):
                _branch_name(name)

    def test_git_wrapper_is_not_shell(self):
        import unittest.mock
        with unittest.mock.patch("development_tools.subprocess.run") as runner:
            runner.return_value = Mock(returncode=0, stdout="", stderr="")
            _git(Path("."), "status", "--short")
            args, kwargs = runner.call_args
            self.assertFalse(kwargs["shell"])
            self.assertEqual(args[0][-2:], ["status", "--short"])
            self.assertEqual(kwargs["timeout"], 15)


if __name__ == "__main__":
    unittest.main()
